// SPDX-License-Identifier: Apache-2.0
//! The machine-readable wire contract, derived from the types that carry it.
//!
//! # Why this exists
//!
//! `docs/PROTOCOL.md` is prose, and prose about a wire format drifts from the
//! format. Before this module a consumer had to read `exec.rs` and `fs.rs` to
//! learn what a body looks like, which makes every field an accident of whichever
//! version of the source they happened to open. Every schema below is generated by
//! `schemars` from the same `Serialize`/`Deserialize` types the handlers use, so
//! the document cannot describe a shape the daemon does not emit — the failure
//! mode of hand-written API docs is not available here.
//!
//! # Why a JSON Schema document rather than OpenAPI 3.1
//!
//! OpenAPI has better tooling, and it was the first choice. It lost on what this
//! contract actually needs to say:
//!
//! * **The status codes are the contract.** 503-before-bootstrap versus 401-wrong-
//!   token versus 400-malformed versus 404-genuinely-absent versus 409-state-
//!   conflict versus 413-too-large is the part a client gets wrong, and each one
//!   was bought with a defect. OpenAPI holds a description string per response,
//!   which is where prose goes to be ignored; here each code carries a slug the
//!   client can branch on next to the meaning.
//! * **The limits are the contract.** `max_body_bytes`, `max_output_bytes`, and
//!   `max_stdin_write_bytes` are read from the *running* `Config`, so an operator
//!   who raised a cap by environment variable is describing their own daemon and
//!   not the defaults. In OpenAPI that is an `x-` extension, at which point the
//!   tooling advantage is gone.
//! * **The lifecycle hooks are not client routes.** They live under a prefix the
//!   platform fixes and a consumer must never call. An OpenAPI `paths` object says
//!   "call these"; a separate `hooks` array says what it means.
//! * **SSE events are typed, and OpenAPI cannot say so.** Three named event types
//!   with three distinct payload schemas on one `text/event-stream` response has no
//!   OpenAPI 3.1 encoding that a generator does anything useful with.
//!
//! So: raw JSON Schema in `$defs`, referenced from a route table that says the
//! things OpenAPI would have made us hide in extensions. Less ceremony, and the
//! load-bearing parts are first-class.

use axum::http::StatusCode;
use schemars::{JsonSchema, Schema, SchemaGenerator, generate::SchemaSettings};
use serde_json::{Map, Value, json};

use crate::config::Config;

/// The protocol version, re-exported from its original path. It lives in the
/// `protocol` crate because a client has to compare against the same constant this
/// document publishes, and two copies of a version number is the drift the number
/// exists to detect.
pub use protocol::PROTOCOL_VERSION;

/// Whether a route requires the bearer token.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Auth {
    /// Bearer token, checked before any body byte is read.
    Bearer,
    /// Unauthenticated and intended for clients: health and this document.
    Open,
    /// Unauthenticated because the platform has no credential to present. Not a
    /// client route — see [`Endpoint::path`].
    PlatformHook,
}

impl Auth {
    fn slug(self) -> &'static str {
        match self {
            Auth::Bearer => "bearer",
            Auth::Open => "none",
            Auth::PlatformHook => "none (platform hook)",
        }
    }
}

/// One status code a route is documented to return, with the meaning a client
/// branches on.
#[derive(Clone, Copy, Debug)]
pub struct Status {
    pub code: StatusCode,
    /// The `error` slug in the JSON body, when there is one. Empty for routes
    /// whose failures carry a plain-text body — the fs routes predate `ErrorBody`
    /// and answer `text/plain`, which is recorded rather than smoothed over.
    pub slug: &'static str,
    pub meaning: &'static str,
}

impl Status {
    const fn new(code: StatusCode, slug: &'static str, meaning: &'static str) -> Self {
        Self {
            code,
            slug,
            meaning,
        }
    }

    fn to_json(self) -> Value {
        json!({
            "code": self.code.as_u16(),
            "error": self.slug,
            "meaning": self.meaning,
        })
    }
}

/// What travels in a request or response body.
///
/// The schema is a function pointer rather than an inline `Schema` because
/// generation needs a `&mut SchemaGenerator` to register the type in `$defs` and
/// hand back a `$ref`; storing the pointer keeps the route table a plain `const`-
/// shaped list instead of something that has to be built inside the generator.
#[derive(Clone, Copy)]
pub struct Payload {
    media_type: &'static str,
    schema: Option<fn(&mut SchemaGenerator) -> Schema>,
    note: &'static str,
}

impl Payload {
    /// No body at all.
    const fn none() -> Self {
        Self {
            media_type: "",
            schema: None,
            note: "",
        }
    }

    /// A JSON body described by `T`.
    fn json<T: JsonSchema>() -> Self {
        Self {
            media_type: "application/json",
            schema: Some(|generator| generator.subschema_for::<T>()),
            note: "",
        }
    }

    /// A body with no JSON shape: raw bytes, a tar stream, or an SSE stream.
    const fn opaque(media_type: &'static str, note: &'static str) -> Self {
        Self {
            media_type,
            schema: None,
            note,
        }
    }

    fn to_json(self, generator: &mut SchemaGenerator) -> Value {
        if self.media_type.is_empty() {
            return Value::Null;
        }
        let mut out = Map::new();
        out.insert("media_type".into(), self.media_type.into());
        if let Some(schema) = self.schema {
            out.insert("schema".into(), schema(generator).to_value());
        }
        if !self.note.is_empty() {
            out.insert("note".into(), self.note.into());
        }
        Value::Object(out)
    }
}

/// One named SSE event on a streaming response.
#[derive(Clone, Copy)]
pub struct SseEvent {
    name: &'static str,
    schema: fn(&mut SchemaGenerator) -> Schema,
    meaning: &'static str,
}

impl SseEvent {
    fn to_json(self, generator: &mut SchemaGenerator) -> Value {
        json!({
            "event": self.name,
            "schema": (self.schema)(generator).to_value(),
            "meaning": self.meaning,
        })
    }
}

/// One route, as both the router registers it and the document describes it.
///
/// The router in [`crate::routes::app`] is *built from* the same list that
/// produces this document, which is the only arrangement where adding a route
/// without documenting it is impossible rather than merely discouraged. A doc
/// field left empty is still a visible omission; a route absent from the list
/// simply does not exist.
#[derive(Clone)]
pub struct Endpoint {
    pub method: &'static str,
    /// Full path as registered, hook prefix included. axum's `{id}` capture
    /// syntax is preserved verbatim: a consumer generating a client wants the
    /// parameter marked, and rewriting it to another convention would be one more
    /// thing that can disagree with the router.
    pub path: String,
    pub auth: Auth,
    pub summary: &'static str,
    pub query: Option<Payload>,
    pub request: Payload,
    pub response: Payload,
    pub statuses: &'static [Status],
    pub sse_events: &'static [SseEvent],
}

/// The bounds a client needs in order to stay inside them.
///
/// Read from the running [`Config`] rather than from the defaults, so an operator
/// who raised a cap by environment variable publishes their own numbers. Without
/// this a client has to discover every cap by tripping it, and two of them (413 on
/// a stdin write, 413 on an archive) are indistinguishable from a transport
/// failure at the moment they fire.
fn limits(config: &Config) -> Value {
    json!({
        "max_body_bytes": config.max_body_bytes,
        "max_output_bytes": config.max_output_bytes,
        "max_stdin_write_bytes": config.max_stdin_write_bytes,
        "max_tar_members": config.max_tar_members,
        "max_tar_bytes": config.max_tar_bytes,
        "stream_replay_bytes": config.stream_buffer_bytes,
        "sse_keepalive_secs": config.sse_keepalive.as_secs_f64(),
        "stdin_write_timeout_secs": config.stdin_write_timeout.as_secs_f64(),
        "exec_ttl_secs": config.exec_ttl.as_secs_f64(),
        "output_linger_secs": config.output_linger.as_secs_f64(),
        "kill_grace_secs": config.kill_grace.as_secs_f64(),
        "max_drain_bytes": config.max_drain_bytes,
    })
}

/// Renders the whole document.
///
/// `endpoints` comes from [`crate::routes::surface`], the same list the router is
/// assembled from.
pub fn document(config: &Config, endpoints: &[Endpoint]) -> Value {
    // draft2020-12 puts definitions under `/$defs`, which is where the `$ref`s
    // this emits point. `for_serialize` is the right contract for a document that
    // describes what the daemon *writes*: it honors `skip_serializing_if`, which
    // is why `PollResponse.result` is documented as absent-when-null rather than
    // as a required null. Request types are generated separately below, under the
    // deserialize contract, because for those the question is what the daemon will
    // *accept* — a field with a serde default is optional on the way in and
    // present on the way out, and one generator cannot say both.
    let mut writes = SchemaSettings::draft2020_12()
        .for_serialize()
        .into_generator();
    let mut reads = SchemaSettings::draft2020_12()
        .for_deserialize()
        .into_generator();

    // Responses and SSE events resolve against `writes`; queries and request
    // bodies against `reads`.
    let routes: Vec<Value> = endpoints
        .iter()
        .map(|endpoint| {
            let mut out = Map::new();
            out.insert("method".into(), endpoint.method.into());
            out.insert("path".into(), endpoint.path.clone().into());
            out.insert("auth".into(), endpoint.auth.slug().into());
            out.insert("summary".into(), endpoint.summary.into());
            if let Some(query) = endpoint.query {
                out.insert("query".into(), query.to_json(&mut reads));
            }
            out.insert("request".into(), endpoint.request.to_json(&mut reads));
            out.insert("response".into(), endpoint.response.to_json(&mut writes));
            out.insert(
                "statuses".into(),
                endpoint
                    .statuses
                    .iter()
                    .copied()
                    .map(Status::to_json)
                    .collect(),
            );
            if !endpoint.sse_events.is_empty() {
                out.insert(
                    "sse_events".into(),
                    endpoint
                        .sse_events
                        .iter()
                        .map(|event| event.to_json(&mut writes))
                        .collect(),
                );
            }
            Value::Object(out)
        })
        .collect();

    let (defs, collisions) = merge_definitions(&mut writes, &mut reads);

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "microvms-agentd wire protocol",
        "daemon_version": crate::routes::VERSION,
        "protocol_version": PROTOCOL_VERSION,
        "version_header": crate::routes::VERSION_HEADER,
        "hook_prefix": crate::routes::HOOK_PREFIX,
        "generated_from": "the daemon's own serde types, via schemars",
        "auth": {
            "scheme": "bearer",
            "header": "authorization",
            "bootstrap": {
                "how": "the platform posts the token to the run hook at launch",
                "before_bootstrap": "503 on every bearer route, never 404",
                "wrong_token": "401",
                "note": "the token is compared on raw bytes in constant time, so a \
                         non-ASCII header is answered rather than dropped",
            },
        },
        "unmatched_path": {
            "code": 404,
            "meaning": "no such route. Bearer routes are behind route_layer, so an \
                        unmatched path falls through to this rather than being \
                        answered 401 — a typo must not send a client chasing \
                        credentials.",
        },
        "limits": limits(config),
        "routes": routes,
        "$defs": defs,
        // Empty in a correct build. A name here means one type generated two
        // different shapes under the serialize and deserialize contracts, so a
        // `$ref` in the document would resolve to whichever won — the artifact
        // test asserts this stays empty rather than trusting that it does.
        "definition_collisions": collisions,
    })
}

/// Folds both generators' definitions into one `$defs` map.
///
/// Reports rather than resolves a name that carries different content in the two
/// contracts. Silently preferring one would publish a shape the daemon does not
/// use on one of the two paths, which is the exact class of error a generated
/// document is supposed to make impossible.
fn merge_definitions(
    writes: &mut SchemaGenerator,
    reads: &mut SchemaGenerator,
) -> (Map<String, Value>, Vec<String>) {
    let mut defs = writes.take_definitions(true);
    let mut collisions = Vec::new();
    for (name, schema) in reads.take_definitions(true) {
        match defs.get(&name) {
            Some(existing) if *existing != schema => collisions.push(name),
            Some(_) => {}
            None => {
                defs.insert(name, schema);
            }
        }
    }
    collisions.sort();
    (defs, collisions)
}

// ---------------------------------------------------------------------------
// Status-code tables.
//
// Spelled out per route rather than composed from shared fragments. The
// repetition is deliberate: 401 and 503 apply to every bearer route, and a reader
// checking "what can this route return" should not have to resolve an inheritance
// chain to find out. These are data, so the cost of the repetition is bytes and
// the benefit is that the document is readable without a legend.
// ---------------------------------------------------------------------------

const UNAUTHORIZED: Status = Status::new(
    StatusCode::UNAUTHORIZED,
    "",
    "the presented bearer token does not match the installed one",
);

const NOT_BOOTSTRAPPED: Status = Status::new(
    StatusCode::SERVICE_UNAVAILABLE,
    "",
    "no token is installed yet, so the control API is closed. Never 404: a client \
     mapping 404 onto \"not found\" would report a phantom absent artifact.",
);

const BODY_TOO_LARGE: Status = Status::new(
    StatusCode::PAYLOAD_TOO_LARGE,
    "",
    "the request body exceeds limits.max_body_bytes, enforced on the wire",
);

const DISK_PRESSURE: Status = Status::new(
    StatusCode::INSUFFICIENT_STORAGE,
    "",
    "the target filesystem is under the configured disk reserve, and the body names \
     the available and reserved byte counts. 507 rather than 500 because a 500 is \
     indistinguishable from a daemon defect and a client retries it, which is right \
     for a defect and actively harmful for a full disk; and rather than 413 because \
     the write is not too large for the protocol, only for the space left.",
);

const UNKNOWN_EXEC: Status = Status::new(
    StatusCode::NOT_FOUND,
    "unknown_exec",
    "no exec is registered under this id, or its entry was collected after an ack",
);

pub const EXEC_START: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "started, or a retry of an already-started exec_id. Idempotent: a retry \
         does not spawn a second child and does not disturb the first one's output.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "malformed_request",
        "the body is not a valid start request, exec_id is empty, timeout_sec is \
         not a positive finite number, or command is empty with shell false",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    BODY_TOO_LARGE,
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "spawn_failed",
        "the child could not be spawned, e.g. ENOENT on argv[0]. Deliberately not \
         404: a client reads 404 here as \"no such exec\".",
    ),
];

pub const EXEC_POLL: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "the current phase, plus the outcome once the exec has exited and before \
         it is acked. Strictly read-only.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    UNKNOWN_EXEC,
];

pub const EXEC_STREAM: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "an SSE stream that replays from ?offset= and then follows live output. \
         Attaching and detaching do not affect the exec.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "malformed_request",
        "offset is not a non-negative integer",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    UNKNOWN_EXEC,
];

pub const EXEC_STDIN: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "bytes written, and eof echoed back so a client can confirm the pipe was \
         closed rather than inferring it",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "malformed_request",
        "the body is not a valid stdin request, data_b64 is not valid base64, or \
         signal is something other than \"eof\"",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    UNKNOWN_EXEC,
    Status::new(
        StatusCode::REQUEST_TIMEOUT,
        "stdin_write_timeout",
        "the child did not read within limits.stdin_write_timeout_secs. Retryable, \
         and some bytes may already have been written.",
    ),
    Status::new(
        StatusCode::CONFLICT,
        "stdin_not_requested",
        "the exec was started without stdin: true, so its stdin is /dev/null. The \
         fix is at start time, which is why this is 409 and not 400.",
    ),
    Status::new(
        StatusCode::GONE,
        "stdin_closed",
        "stdin was already closed by an earlier eof, or the child stopped reading. \
         410 rather than 409: retrying will never succeed.",
    ),
    Status::new(
        StatusCode::PAYLOAD_TOO_LARGE,
        "stdin_write_too_large",
        "the decoded write exceeds limits.max_stdin_write_bytes",
    ),
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "stdin_write_failed",
        "the write to the pipe failed for a reason other than a broken pipe",
    ),
];

pub const EXEC_ACK: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "output released and the TTL clock started. This is the only way output \
         leaves the daemon's custody.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    UNKNOWN_EXEC,
    Status::new(
        StatusCode::CONFLICT,
        "still_running",
        "the exec has not exited and output is still being written. A silent \
         success here would drop it.",
    ),
    Status::new(
        StatusCode::CONFLICT,
        "already_acked",
        "an earlier ack released the output. 200 with an empty body would read as \
         \"the command produced no output\".",
    ),
];

pub const EXEC_KILL: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "the process group was signalled, or killed is false because it had \
         already exited — which is the outcome a kill was asking for",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    UNKNOWN_EXEC,
];

pub const FS_READ_FILE: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "the file's bytes, streamed rather than buffered — or the requested line \
         range of them, also streamed. A range whose end_line is past the last line \
         answers 200 through EOF, never 416: 416 is about a range the file cannot \
         satisfy, and reading through EOF is the harness contract.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "",
        "the path query parameter is missing, it names a directory — use \
         /v1/fs/tar for that — start_line or end_line is not an integer, \
         start_line is 0 (the range is 1-based), or end_line is before \
         start_line. Never 404 for any of them: a protocol error must not look \
         like an absent file.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    Status::new(
        StatusCode::NOT_FOUND,
        "",
        "the path is genuinely absent. The one place in the fs surface where a \
         client's FileNotFoundError is the right mapping.",
    ),
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "",
        "the file could not be opened or stat'ed",
    ),
];

pub const FS_WRITE_FILE: &[Status] = &[
    Status::new(StatusCode::NO_CONTENT, "", "written, with the mode applied"),
    Status::new(
        StatusCode::BAD_REQUEST,
        "",
        "the path query parameter is missing, or mode is not a valid octal file \
         mode. Checked before a byte lands, so a rejected mode leaves nothing \
         behind.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    BODY_TOO_LARGE,
    DISK_PRESSURE,
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "",
        "the parent could not be created, or the write or chmod failed",
    ),
];

pub const FS_READ_TAR: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "an uncompressed tar of the tree, streamed from a spool file. Symlinks are \
         packed as symlinks, matching what extraction accepts.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "",
        "the path query parameter is missing, or it is not a directory — use \
         /v1/fs/file for that",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    Status::new(
        StatusCode::NOT_FOUND,
        "",
        "the directory is genuinely absent",
    ),
    Status::new(
        StatusCode::PAYLOAD_TOO_LARGE,
        "",
        "the tree exceeds limits.max_tar_members or limits.max_tar_bytes, measured \
         by a walk before anything is allocated",
    ),
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "",
        "the tree could not be walked or packed",
    ),
];

pub const FS_WRITE_TAR: &[Status] = &[
    Status::new(StatusCode::NO_CONTENT, "", "extracted under ?path="),
    Status::new(
        StatusCode::BAD_REQUEST,
        "",
        "the path query parameter is missing or not absolute, the body was \
         truncated, or a member violated the extraction contract — an escaping \
         path, an absolute or out-of-tree link target, or a device or fifo member. \
         The refused member's name is in the body.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
    Status::new(
        StatusCode::PAYLOAD_TOO_LARGE,
        "",
        "the archive exceeds limits.max_body_bytes on the wire, or \
         limits.max_tar_members or limits.max_tar_bytes once decoded",
    ),
    DISK_PRESSURE,
    Status::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        "",
        "extraction failed for a filesystem reason",
    ),
];

pub const HEALTH: &[Status] = &[Status::new(
    StatusCode::OK,
    "",
    "always, whether or not the daemon is bootstrapped. bootstrapped is how a \
     client learns whether the control API is open yet; busy is how an \
     orchestrator outside the VM learns whether a workload is still running, so \
     its own poll doubles as the inbound traffic the platform's idle policy \
     measures. An in-guest request cannot serve that purpose: the endpoint proxy \
     terminates outside the guest.",
)];

/// The TCP relay's statuses. Its real outcomes are **close codes**, not statuses.
///
/// A WebSocket route has exactly one success status and then leaves HTTP behind, so the
/// interesting failures — nothing listening, a bad port, a mid-relay error — arrive as close
/// codes in `tunnel::close`. Recorded here rather than left implicit, because a consumer
/// reading only this table would otherwise conclude the route has no failure modes.
pub const TUNNEL_OPEN: &[Status] = &[
    Status::new(
        StatusCode::SWITCHING_PROTOCOLS,
        "",
        "the upgrade succeeded. The guest dial happens AFTER the upgrade, so a 101 \
         does not yet mean the guest port answered: a refused dial arrives as close \
         code 4502 with a reason naming the port. That ordering is deliberate — on the \
         endpoint path every WebSocket failure a caller can observe is 1006 with no \
         reason, so an HTTP 502 here would be invisible to the only client that \
         matters.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "malformed_request",
        "?port is absent or is not a u16. Port 0 parses and is refused after the \
         upgrade with close code 4400, because a caller that named it deserves a \
         reason rather than a parse error.",
    ),
    UNAUTHORIZED,
    NOT_BOOTSTRAPPED,
];

pub const SCHEMA: &[Status] = &[Status::new(
    StatusCode::OK,
    "",
    "this document. Unauthenticated by design: a client needs the contract before \
     it has a token, and none of it is secret.",
)];

pub const HOOK_ACK: &[Status] = &[Status::new(
    StatusCode::OK,
    "",
    "acknowledged. The platform terminates the VM on any other status, so there is \
     no failure a hook can usefully report.",
)];

pub const HOOK_RUN: &[Status] = &[
    Status::new(
        StatusCode::OK,
        "",
        "the token was installed, or an identical token was replayed. A replay is \
         success because the platform may retry its own hook, and answering 409 \
         would fail a launch that is fine.",
    ),
    Status::new(
        StatusCode::BAD_REQUEST,
        "",
        "the body is not JSON, carries no runHookPayload, the payload is not a \
         JSON object, agent_token is absent or not a string or empty, env is \
         present but not an object, or an env value is not a string. The body \
         names which of those it was, and never quotes a value — the payload \
         carries the token. An unknown key is NOT one of these: it is ignored, \
         because the platform terminates the VM on any 400 here, before any \
         traffic is forwarded, so a newer client's unrecognised field must not \
         kill the launch.",
    ),
    Status::new(
        StatusCode::CONFLICT,
        "",
        "a different token is already installed. Refused, and nothing changes — \
         including the launch env, which only the first successful bootstrap \
         sets: bootstrap is one-shot so a losing racer never replaces the \
         winner's token, and cannot rewrite the environment every later child \
         runs in either.",
    ),
];

// ---------------------------------------------------------------------------
// Payload and SSE-event constructors, so the route table in `routes.rs` reads as
// a table rather than as generator plumbing.
// ---------------------------------------------------------------------------

/// No body.
pub const fn no_body() -> Payload {
    Payload::none()
}

/// A JSON body shaped by `T`.
pub fn json_body<T: JsonSchema>() -> Payload {
    Payload::json::<T>()
}

/// Raw bytes with no JSON shape.
pub const fn octet_stream(note: &'static str) -> Payload {
    Payload::opaque("application/octet-stream", note)
}

/// An uncompressed tar stream.
pub const fn tar_stream(note: &'static str) -> Payload {
    Payload::opaque("application/x-tar", note)
}

/// An SSE stream. The typed events are listed separately on the endpoint.
pub const fn sse_stream(note: &'static str) -> Payload {
    Payload::opaque("text/event-stream", note)
}

/// Query parameters shaped by `T`.
pub fn query<T: JsonSchema>() -> Payload {
    Payload {
        media_type: "application/x-www-form-urlencoded",
        schema: Some(|generator| generator.subschema_for::<T>()),
        note: "",
    }
}

/// One typed SSE event.
///
/// `const fn` so the event table can be a `static`: the closure captures nothing
/// and coerces to a plain function pointer, and `T` is resolved at the call site.
pub const fn sse_event<T: JsonSchema>(name: &'static str, meaning: &'static str) -> SseEvent {
    SseEvent {
        name,
        schema: |generator| generator.subschema_for::<T>(),
        meaning,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::routes;

    fn doc() -> Value {
        document(&Config::default(), &routes::surface_docs())
    }

    #[test]
    fn every_type_generates_one_shape_across_both_contracts() {
        // A name here means a `$ref` in the document resolves to whichever
        // contract happened to win, so the document would describe a shape the
        // daemon does not use on one of the two paths.
        assert_eq!(
            doc()["definition_collisions"],
            json!([]),
            "a type generated different schemas for serialize and deserialize"
        );
    }

    /// Every `$ref` the routes emit has to resolve inside `$defs`. A dangling ref
    /// is the failure mode of a two-generator setup, and it is invisible until a
    /// consumer's tooling chokes on it.
    #[test]
    fn every_reference_resolves_inside_the_document() {
        let doc = doc();
        let defs = doc["$defs"].as_object().expect("$defs is an object");
        let mut refs = Vec::new();
        collect_refs(&doc, &mut refs);
        assert!(!refs.is_empty(), "the document emitted no $refs at all");
        for reference in refs {
            let name = reference
                .strip_prefix("#/$defs/")
                .unwrap_or_else(|| panic!("unexpected $ref target {reference}"));
            assert!(defs.contains_key(name), "$ref {reference} does not resolve");
        }
    }

    fn collect_refs(value: &Value, out: &mut Vec<String>) {
        match value {
            Value::Object(map) => {
                for (key, child) in map {
                    if key == "$ref" {
                        if let Some(target) = child.as_str() {
                            out.push(target.to_string());
                        }
                    } else {
                        collect_refs(child, out);
                    }
                }
            }
            Value::Array(items) => items.iter().for_each(|item| collect_refs(item, out)),
            _ => {}
        }
    }

    /// schemars honors `#[serde(rename_all = "snake_case")]`, which is the whole
    /// reason the schema is derived rather than written. If it did not, `Phase`
    /// would be published as `Running` while the daemon emits `running`.
    ///
    /// schemars 1.x renders a unit-variant enum two ways, and which one you get
    /// depends on something as incidental as whether the variants carry doc
    /// comments: with them it emits `oneOf` and a `const` per variant so each
    /// description has somewhere to live, without them a flat `enum` array. `Phase`
    /// is documented per variant and `StreamKind` is not, so both forms appear in
    /// one document — a consumer's validator has to accept either, and so does this.
    #[test]
    fn serde_renames_reach_the_published_schema() {
        assert_eq!(
            variant_names(&doc()["$defs"]["Phase"]),
            ["running", "exited", "acked"],
            "the published Phase does not match what serde emits"
        );
        assert_eq!(
            variant_names(&doc()["$defs"]["StreamKind"]),
            ["stdout", "stderr"],
        );
    }

    /// The serialized names of a unit-variant enum, in either rendering.
    fn variant_names(schema: &Value) -> Vec<String> {
        if let Some(flat) = schema["enum"].as_array() {
            return flat
                .iter()
                .map(|name| {
                    name.as_str()
                        .unwrap_or_else(|| panic!("enum entry is not a string: {name}"))
                        .to_string()
                })
                .collect();
        }
        schema["oneOf"]
            .as_array()
            .unwrap_or_else(|| panic!("expected an enum or oneOf, got {schema}"))
            .iter()
            .map(|variant| {
                variant["const"]
                    .as_str()
                    .unwrap_or_else(|| panic!("variant has no const: {variant}"))
                    .to_string()
            })
            .collect()
    }

    /// The run hook's envelope key is `runHookPayload`, not `run_hook_payload`.
    /// Getting this wrong makes the platform terminate the VM with a 400 before
    /// any traffic is forwarded, so it is the single field most worth publishing
    /// from the type rather than from memory.
    #[test]
    fn the_run_hook_envelope_publishes_the_platforms_own_key() {
        let doc = doc();
        let envelope = &doc["$defs"]["RunHookEnvelope"]["properties"];
        assert!(
            envelope.get("runHookPayload").is_some(),
            "the envelope key was published unrenamed: {envelope}"
        );
        assert!(envelope.get("run_hook_payload").is_none());
    }

    /// The limits are read from the running config, not from the defaults, so an
    /// operator who raised a cap publishes their own number.
    #[test]
    fn limits_track_the_running_configuration() {
        let config = Config {
            max_stdin_write_bytes: 4321,
            max_output_bytes: 7654,
            ..Config::default()
        };
        let doc = document(&config, &routes::surface_docs());
        assert_eq!(doc["limits"]["max_stdin_write_bytes"], json!(4321));
        assert_eq!(doc["limits"]["max_output_bytes"], json!(7654));
    }

    #[test]
    fn the_document_names_both_versions_and_the_header_that_carries_one() {
        let doc = doc();
        assert_eq!(doc["daemon_version"], json!(routes::VERSION));
        assert_eq!(doc["protocol_version"], json!(PROTOCOL_VERSION));
        assert_eq!(doc["version_header"], json!(routes::VERSION_HEADER));
    }
}
