# SPDX-License-Identifier: Apache-2.0
# GENERATED by ./scripts/generate-py-stubs.py — do not edit by hand.
#
# Regenerate with `mise run stubs`; `mise run stubs:check` fails when this file no
# longer matches the Rust surface it describes. Signatures and docstrings above the
# exceptions come from pyo3's introspection of `microvms-py/src/`; the exceptions
# come from importing the built module, because `create_exception!` emits no
# introspection record.
"""
The MicroVMs client, as Python sees it.
"""

from collections.abc import Sequence
from typing import Any, Final, final

@final
class Amount:
    """
    What a line item's cost can be: an estimate, or unpriced.
    
    A class rather than a union, because a union in Python is a documentation convention
    and this has to be something a caller can branch on. `kind` is the stable tag
    (`"estimated-usd"` / `"unpriced"`), `usd` is `None` for the unpriced case, and
    `unpriced` is `None` for the priced one — so exactly one of the two is present and a
    reader who checks either has handled both.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def kind(self, /) -> str:
        """
        `"estimated-usd"` or `"unpriced"` — the tag `cli.py` puts in `amount.kind`.
        """
    @property
    def unpriced(self, /) -> Unpriced |None:
        """
        The unpriced half, or `None` when the line was priced.
        """
    @property
    def usd(self, /) -> EstimatedUsd |None:
        """
        The estimate, or `None` when there is no published rate.
        
        `None` rather than a zero, which is the same decision as the JSON omitting the
        `usd` key: a zero gets summed by anything permissive, and that is the one
        arithmetic this module refuses to enable.
        """

@final
class BaseImage:
    """
    The platform's managed base image, paired with the Dockerfile `FROM` it goes with.
    
    One class rather than two strings, because the two **must** agree and used to be able
    to disagree: the Python client's default named the managed base for `baseImageArn` while
    its Dockerfile hardcoded an unrelated registry literal in its `FROM`, so changing either
    left the other pointing somewhere else.
    """
    def __new__(cls, /, name: str, docker_ref: str, working_dir: str = "") -> BaseImage:
        """
        A base a caller built themselves.
        
        `working_dir` is what `docker inspect` reports for `WorkingDir`, and empty means the
        image declares none. It is a parameter because a caller with a purpose-built image
        is the only one who can say what theirs declares — this client cannot read it
        without pulling the manifest. Getting it wrong is what
        `inherit_workdir` refuses on.
        """
    def __repr__(self, /) -> str: ...
    @staticmethod
    def al2023() -> BaseImage:
        """
        The managed base every `docs/PLATFORM.md` measurement from 2026-08-06 onward used.
        """
    @property
    def docker_ref(self, /) -> str:
        """
        Goes into the Dockerfile `FROM` — the registry ref measured alongside `name`.
        """
    @property
    def name(self, /) -> str:
        """
        Goes into `baseImageArn` — the platform's managed base, not a registry ref.
        """
    @property
    def working_dir(self, /) -> str: ...

@final
class BuildHookTimeout:
    """
    A timeout for the `ready` or `validate` image-build hook: 1..=3600 seconds.
    """
    MAX_SECS: Final[int]
    """
    The service ceiling for this family: 3600.
    """
    def __new__(cls, /, seconds: int) -> BuildHookTimeout:
        """
        A build-family timeout, or a refusal naming both ceilings.
        """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def seconds(self, /) -> int: ...

@final
class CostReport:
    """
    Per-phase attribution for one sandbox, measured or projected.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def by_phase(self, /, phase: str) -> list[LineItem]:
        """
        The line items belonging to one phase.
        
        The string is judged by the core's own [`CostPhase::from_str`], which is where the
        closed set lives. This module used to carry its own seven-element table for it — a
        parallel list over an enum, which would have gone stale the first time a phase was
        added and would have disagreed with the JS binding's identical copy in whichever
        direction was edited first.
        """
    @property
    def complete(self, /) -> bool:
        """
        False whenever any phase has no published rate.
        """
    @property
    def fully_measured(self, /) -> bool:
        """
        True only if every duration was timed. An estimate is never this.
        """
    @property
    def items(self, /) -> list[LineItem]: ...
    @property
    def label(self, /) -> str: ...
    @property
    def priced(self, /) -> list[LineItem]:
        """
        The line items with a published rate.
        """
    @property
    def rates(self, /) -> RateTable: ...
    def render(self, /) -> str:
        """
        Plain text, leading with what the dollars are rather than with the dollars.
        """
    @property
    def size(self, /) -> SizeClass: ...
    @property
    def staleness(self, /) -> str |None:
        """
        The staleness warning the table carried when this was computed.
        """
    def to_dict(self, /) -> dict:
        """
        The `cli.py:688 report_to_dict` shape, key for key.
        """
    @property
    def total(self, /) -> Total:
        """
        The total, which is a lower bound whenever anything is unpriced.
        """
    @property
    def unpriced(self, /) -> list[LineItem]:
        """
        The line items with no published rate.
        """

@final
class Duration:
    """
    Seconds, plus how we know them.
    
    There is **no** `__new__`: naming a provenance is the only way to build one, and the
    two named constructors are the only doors. `cost.py` achieved the same thing with a
    field that had no default, so `Duration(3600)` raised `TypeError` — here there is
    nothing to call, which is one rung stronger.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def is_measured(self, /) -> bool:
        """
        True only for a timed span. What `CostReport.fully_measured` reads.
        """
    @staticmethod
    def measured(seconds: float) -> Duration:
        """
        A timed phase: a clock ran and this is what it read.
        
        Fallible because the float is — a negative or non-finite figure has no reading as
        a duration, and the refusal is the core's `duration_of_secs_f64`.
        """
    @staticmethod
    def projected(seconds: float) -> Duration:
        """
        A hypothetical phase: an estimate's input, or a documented minimum nobody timed.
        """
    @property
    def provenance(self, /) -> str:
        """
        `"measured"` or `"projected"`, spelled as the Python `StrEnum` member.
        """
    @property
    def seconds(self, /) -> float:
        """
        The span in seconds, without its label.
        
        A float here and not on the money types, deliberately: seconds really are a
        measurement a caller does arithmetic on, and the core's own
        `break_even_seconds_f64` makes the same distinction for the same reason.
        """

@final
class EstimatedUsd:
    """
    Dollars derived from published rates. Not the bill.
    
    # There is no way to get a number out of this
    
    No `__float__`, no `__int__`, no `__index__`, no `__add__`. [`Self::amount`] answers a
    **string** — the decimal figure at full precision — so `float(usd)` raises
    `TypeError`, `usd + usd` raises `TypeError`, and the cheapest laundering spelling
    (`f"${float(x):.2f}"`) does not run. The core makes this a compile error; the closest
    Python equivalent is an absence, and this is it.
    
    A caller who genuinely needs arithmetic writes `Decimal(usd.amount)`, which is one
    visible step, keeps the type name at the call site, and is a decision a reviewer sees.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str:
        """
        `~$X (estimated)` — the label travels with the figure, because a number copied out
        of a terminal loses its docstring.
        """
    @property
    def amount(self, /) -> str:
        """
        The figure as an exact decimal **string**.
        
        A string and not a float, which is the whole of COST-2 at this boundary. The core
        carries a `rust_decimal::Decimal` and the exact spelling of it is what survives
        into `Decimal(...)` on the Python side; an f64 would already have lost the
        exactness the type exists to hold.
        """
    @property
    def display_amount(self, /) -> str:
        """
        The figure at display precision: two places at a dollar or more, six below.
        
        A create-and-destroy suite's compute cost lives in the sixth decimal place while a
        warm pool's monthly bill lives in the second, and one fixed precision cannot show
        both.
        """

@final
class ExecHandle:
    """
    One exec, addressed by its caller-minted id.
    
    The id is the idempotency key, so a handle survives a process restart: rebuild it
    through `Session.exec(exec_id)` and every method still addresses the same server-side
    exec.
    """
    def __repr__(self, /) -> str: ...
    def ack(self, /) -> ExecResult:
        """
        Releases the buffered output and starts the TTL clock.
        """
    def close_stdin(self, /) -> StdinAck:
        """
        Sends EOF. Nothing else closes stdin: the daemon's copy of the pipe outlives the
        child's wait, so a child blocked reading stdin hangs until its timeout otherwise.
        """
    @property
    def exec_id(self, /) -> str: ...
    def kill(self, /) -> bool:
        """
        Signals the whole process group. `False` means nothing was signalled because the
        child had already been reaped — which is the outcome a kill wanted.
        """
    def poll(self, /) -> ExecResult:
        """
        Reads current status and output. Read-only server-side; safe to spin on.
        """
    def stream(self, /, *, offset: int = 0, reconnect: bool = True, max_reconnects: int |None = None, error_on_gap: bool = False, idle_timeout: float |None = None) -> ExecStream:
        """
        An iterator over output as it arrives, reconnecting at the last good offset.
        
        `error_on_gap=True` turns an evicted byte range into an exception instead of a
        `Gap` event, which is what a caller that must have complete output wants.
        `reconnect=False` ends the iterator at a cut instead, for a caller doing its own
        reconnection.
        """
    def wait(self, /, timeout: float = ...) -> ExecResult:
        """
        Polls until the exec is done, or raises `TimeoutError`.
        
        A timeout has not touched the exec — polling is read-only and output lives until
        it is acked — so a caller that gives up can come back and poll again.
        """
    def wait_and_ack(self, /, timeout: float = ...) -> ExecResult:
        """
        Wait, then ack, returning the result that carries the output.
        
        Which result comes back matters: the ack response carries the released output and
        a poll issued after the ack reports `acked` with none, so returning the wrong one
        is a silent empty-output bug. The core sequences it.
        """
    def write_stdin(self, /, data: bytes, *, eof: bool = False) -> StdinAck:
        """
        Writes to the child's stdin. Requires the exec to have been started with
        `stdin=True`, or the daemon answers 409.
        
        `eof` in the same call is the common case for feeding a prompt: two round trips
        would leave a window where the child has the bytes but not the EOF that says the
        input is complete.
        """

@final
class ExecResult:
    """
    An exec's phase and, once it has one, its outcome.
    
    `stdout` and `stderr` are `str` because the daemon's `Outcome` carries them as strings
    — the protocol crate's shape, not a choice made here. `exit_code` and `signal` are
    `None` rather than sentinel integers, which is the same distinction `models.py` makes:
    a signal death has no exit code, and zero is not "no signal".
    """
    def __repr__(self, /) -> str: ...
    @property
    def done(self, /) -> bool:
        """
        Whether the exec has finished, whichever way.
        """
    @property
    def exec_id(self, /) -> str: ...
    @property
    def exit_code(self, /) -> int |None:
        """
        `None` when the child died to a signal rather than exiting.
        """
    @property
    def ok(self, /) -> bool:
        """
        Whether the command exited zero. False for a signal death and for a still-running
        exec, since neither is a success.
        """
    @property
    def phase(self, /) -> str:
        """
        `"running"`, `"exited"`, or `"acked"`.
        """
    @property
    def signal(self, /) -> int |None:
        """
        The signal that killed the child, when one did.
        """
    @property
    def stderr(self, /) -> str: ...
    @property
    def stdout(self, /) -> str: ...
    @property
    def truncated(self, /) -> bool:
        """
        Set when either stream hit the output cap and was cut. A flag rather than a
        sentinel inside the bytes, which would be indistinguishable from output that
        happens to contain it.
        """
    @property
    def writers_may_be_alive(self, /) -> bool:
        """
        Set when the post-exit linger deadline expired with the pipes still open: some
        grandchild is alive and may write more that nobody will see.
        """

@final
class ExecStream:
    """
    A Python iterator over an exec's output.
    
    See the module docs for why this is a task and a bounded channel rather than a stored
    future. `receiver` is behind a `Mutex` because `#[pyclass]` methods take `&self` when
    the class is shared, and `recv` needs `&mut`; the lock is held only across one `recv`
    and never across a Python callback, so it cannot deadlock against the GIL.
    """
    def __iter__(self, /) -> ExecStream: ...
    def __next__(self, /) -> Any |None:
        """
        The next event, or `StopIteration` when the stream ends.
        
        Blocks with the GIL released, so another Python thread can run while this one
        waits on the daemon.
        """

@final
class Exit:
    """
    The terminal event. Its **absence** is what distinguishes a cut connection from a
    finished command — the byte sequences are otherwise identical.
    """
    def __repr__(self, /) -> str: ...
    @property
    def exit_code(self, /) -> int |None: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def offset(self, /) -> int:
        """
        Total bytes published. A total rather than a position to resume at, which is why
        `Exit` has no `end` getter while `Output` and `Gap` both do.
        """
    @property
    def signal(self, /) -> int |None: ...
    @property
    def truncated(self, /) -> bool: ...
    @property
    def writers_may_be_alive(self, /) -> bool: ...

@final
class Gap:
    """
    A byte range that is gone for good — the replay ring evicted it, or this subscriber
    lagged the live channel.
    
    A typed event rather than a log line, because the alternative is reading a truncated
    log as a complete one. `start` is inclusive and `end` exclusive, so `end` is where a
    cursor resumes.
    """
    def __repr__(self, /) -> str: ...
    @property
    def end(self, /) -> int: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def size(self, /) -> int: ...
    @property
    def start(self, /) -> int: ...

@final
class Health:
    """
    The daemon's liveness answer. `bootstrapped` is the useful field.
    """
    def __repr__(self, /) -> str: ...
    @property
    def available_bytes(self, /) -> int |None:
        """
        Bytes available to an unprivileged writer, or `None` when free space could not be
        measured.
        
        `None` is deliberately distinct from zero: unmeasurable is not full, and a monitor
        that conflated them would page on a missing `statvfs`.
        """
    @property
    def bootstrapped(self, /) -> bool:
        """
        Whether the run hook has landed and the control API is open.
        """
    @property
    def busy(self, /) -> bool:
        """
        Whether any exec is still running.
        
        For an orchestrator *outside* the VM deciding whether to keep it alive. The
        platform measures idleness by inbound traffic through the endpoint proxy, which
        terminates outside the guest, so an in-guest keepalive cannot reset the idle
        timer — polling this from outside is both the traffic and the decision. An exec
        that exited and is awaiting an ack is not busy.
        """
    @property
    def execs(self, /) -> int:
        """
        How many execs are registered, in any phase. `busy` false with a non-zero count
        is a VM holding unacked output somebody still has to collect.
        """
    @property
    def identity_degraded(self, /) -> bool:
        """
        Whether any startup identity repair step failed — a duplicate machine-id or
        boot_id still in place from the shared image.
        """
    @property
    def identity_repaired(self, /) -> bool:
        """
        False when identity repair was switched off by config. Separate from `degraded` so
        a monitor can tell "opted out" from "nothing to do".
        """
    @property
    def reserve_bytes(self, /) -> int |None:
        """
        Bytes that must stay free before a write is refused. Zero means the guard is off.
        """
    @property
    def under_pressure(self, /) -> bool |None:
        """
        Whether a write would be refused right now. Precomputed by the daemon so every
        consumer applies the same comparison the write path does.
        """
    @property
    def version(self, /) -> str:
        """
        The daemon's own version, distinct from the protocol version.
        """

@final
class Image:
    """
    A built image, and the log group the service created alongside it.
    """
    def __repr__(self, /) -> str: ...
    @property
    def build_log_group(self, /) -> str:
        """
        `/aws/lambda-microvms/<image-name>`.
        
        The service creates this itself, so no Terraform stack owns it and
        `terraform destroy` leaves it behind — "the stack destroyed cleanly" is not "the
        account is clean". Six accumulated before anyone noticed.
        """
    @property
    def identifier(self, /) -> str:
        """
        The image ARN, which is what `imageIdentifier` takes.
        """
    @property
    def log_stream(self, /) -> str |None:
        """
        The resolved exact log stream this build's logs went to, when `log_stream` was
        configured on the build — the configured prefix plus the per-build `/<16 hex>`
        discriminator the client appends. `None` for an unconfigured build (the service
        names the streams randomly).
        
        This is the only copy of the resolved name: the discriminator is minted fresh
        inside the create call, so a caller who wants to read their build's logs reads it
        here or never.
        """
    @property
    def name(self, /) -> str: ...
    @property
    def size(self, /) -> SizeClass:
        """
        The class the requested baseline selected.
        
        Carried on the image because billing follows the baseline requested at *create*
        time, and by the time anyone asks what a run cost the request is gone.
        """
    @property
    def state(self, /) -> str: ...
    @property
    def version(self, /) -> str: ...

@final
class LineItem:
    """
    One phase's one billing line: what was consumed, and what that costs.
    
    `quantity` is a string for the same reason `EstimatedUsd.amount` is: division by 730
    hours yields 28 significant digits and the exact figure is what lets a reader check
    the arithmetic against the rate table, which is the only defence against a rate that
    drifts without anyone noticing.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def amount(self, /) -> Amount: ...
    @property
    def display_quantity(self, /) -> str:
        """
        The quantity at display precision, for a column a human scans.
        """
    @property
    def duration(self, /) -> Duration |None: ...
    @property
    def line(self, /) -> str |None:
        """
        The AWS billing line, or `None` for a phase with no published rate to attribute
        it to.
        """
    @property
    def note(self, /) -> str: ...
    @property
    def phase(self, /) -> str:
        """
        The lifecycle phase, as the Python `StrEnum` spells it.
        """
    @property
    def quantity(self, /) -> str:
        """
        The consumed quantity, exact, as a string.
        """
    def to_dict(self, /) -> dict:
        """
        The `cli.py` `_line_to_dict` shape. An unpriced line has **no** `usd` key at all.
        """
    @property
    def unit(self, /) -> str: ...

@final
class OutputChunk:
    """
    Output bytes, with the offset they start at.
    
    `data` is `bytes` and not `str`: exec output is arbitrary bytes, and a decode here
    would be a lossy step the caller cannot see. `end` is where a cursor resumes.
    """
    def __repr__(self, /) -> str: ...
    @property
    def data(self, /) -> bytes: ...
    @property
    def end(self, /) -> int:
        """
        One past this chunk's last byte: `offset + len(data)`.
        """
    @property
    def kind(self, /) -> str:
        """
        `"output"` — the tag beside `isinstance`, so a caller can branch either way.
        """
    @property
    def offset(self, /) -> int: ...
    @property
    def stream(self, /) -> str:
        """
        `"stdout"` or `"stderr"`. Both share one offset space, so a caller holds one
        cursor rather than two that can disagree about ordering.
        """
    def text(self, /) -> str:
        """
        The bytes as text, replacing anything undecodable.
        
        A method rather than a getter on `data`, so the lossy step is a call a reader sees
        — the same reasoning as the core's `break_even_seconds_f64`.
        """

@final
class RateTable:
    """
    The pinned rate table, and everything it says about itself.
    
    The rates are exact decimal **strings** for the same reason the money types are: they
    are figures like `0.0000276944` and an f64 round trip through Python would make a
    report irreconcilable against the page it came from.
    """
    def __repr__(self, /) -> str: ...
    def age_days(self, /) -> int:
        """
        How many days ago these rates were read, against today UTC.
        """
    @property
    def bills_vcpu_and_memory_separately(self, /) -> bool:
        """
        True: vCPU and memory are two line items, as the pricing page prices them.
        """
    @property
    def free_tier(self, /) -> bool:
        """
        False: no published MicroVMs free tier. The Lambda one is Functions-only.
        """
    @property
    def gb_second(self, /) -> str: ...
    @property
    def minimum_billing_increment_sec(self, /) -> float |None:
        """
        `None` means **not published**, not one second. Nothing rounds a duration up,
        because inventing an increment would overcharge every short exec.
        """
    @property
    def minimum_retention_seconds(self, /) -> float:
        """
        Snapshot storage bills at least this long however briefly the snapshot exists.
        """
    @property
    def per_request(self, /) -> str:
        """
        Zero: MicroVMs bills per second with no per-request charge.
        """
    @staticmethod
    def pinned() -> RateTable:
        """
        us-east-1, read 2026-08-07, as recorded in `docs/PLATFORM.md`.
        
        There is deliberately no constructor taking rates. The core's `RateTable` has
        private rate fields and exactly two doors — this one and `from_catalog`, which
        refuses a catalog whose ARM compute line is missing rather than substituting the
        x86 one (COST-9, 17.9% higher). A binding constructor taking five numbers would
        reopen precisely that.
        """
    @property
    def region(self, /) -> str: ...
    @property
    def retrieved(self, /) -> str:
        """
        ISO 8601, matching the Python's `retrieved.isoformat()` so the two are diffable.
        """
    @property
    def snapshot_read_gb(self, /) -> str: ...
    @property
    def snapshot_write_gb(self, /) -> str: ...
    @property
    def source_url(self, /) -> str: ...
    def staleness(self, /) -> str |None:
        """
        The staleness warning, or `None` when the table is fresh.
        """
    @property
    def storage_gb_month(self, /) -> str:
        """
        Per GB-month. The one derived figure: the API quotes per GB-hour and this is that
        times 730.
        """
    @property
    def vcpu_second(self, /) -> str: ...

@final
class Region:
    """
    An AWS region, closed over the five that run MicroVMs plus a named escape hatch.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def ap_northeast_1() -> Region: ...
    @staticmethod
    def eu_west_1() -> Region: ...
    @property
    def is_supported(self, /) -> bool:
        """
        Whether this is one of the five rather than an opted-into unlisted name.
        """
    @property
    def name(self, /) -> str:
        """
        The wire spelling, which is also the endpoint's middle segment.
        """
    @staticmethod
    def parse(name: str) -> Region:
        """
        One of the five, or a refusal naming the null-message trap.
        
        The boundary a region name arrives at from an environment variable or a config
        file, where it is still a string. The refusal is the core's `FromStr`, message and
        all — this is a call, not a check written here.
        """
    @staticmethod
    def supported() -> list[Region]:
        """
        Every region this client has seen carry MicroVMs.
        """
    @staticmethod
    def unlisted(name: str) -> Region:
        """
        Opts into a region this client has not seen carry MicroVMs.
        
        **This costs you the diagnostic.** If the region does not run MicroVMs, the first
        control-plane call answers `AccessDeniedException` with a null message, and you
        will spend the next hour reading an IAM policy that is correct. Named rather than a
        flag so a reader of the call site can see the opt-in.
        
        A supported name handed here comes back as its proper region, so
        `Region.unlisted("us-east-1") == Region.us_east_1()`.
        """
    @staticmethod
    def us_east_1() -> Region: ...
    @staticmethod
    def us_east_2() -> Region: ...
    @staticmethod
    def us_west_2() -> Region: ...

@final
class ResidencyComparison:
    """
    Running versus suspended for the same VM over the same wall time.
    """
    def __str__(self, /) -> str: ...
    def break_even_seconds(self, /) -> str:
        """
        How long a VM must stay suspended for the cycle to pay for itself, exact, as a
        string.
        
        The number a pool scheduler actually needs, and the one a bare "100x cheaper"
        headline hides.
        """
    def break_even_seconds_float(self, /) -> float:
        """
        The break-even hold as a float, for a JSON envelope. **Lossy, and named so.**
        
        Seconds, not dollars: no money figure has a float accessor anywhere in this
        module.
        """
    @property
    def cycles(self, /) -> int: ...
    @property
    def hold(self, /) -> Duration:
        """
        The wall time both sides cover. Always projected: a comparison is a hypothetical
        about a hold nobody has taken yet.
        """
    def per_cycle(self, /) -> EstimatedUsd:
        """
        One suspend/resume: a snapshot write plus a read, per GB.
        
        On the comparison because without it the honest conclusion inverts — "suspend
        constantly" reads as free.
        """
    @property
    def ratio(self, /) -> str:
        """
        How many times more the running VM costs, as an exact decimal string.
        """
    def render(self, /) -> str: ...
    @property
    def running(self, /) -> CostReport: ...
    @property
    def size(self, /) -> SizeClass: ...
    @property
    def suspended(self, /) -> CostReport: ...

@final
class RunHookTimeout:
    """
    A timeout for the `run`, `resume`, `suspend`, or `terminate` hook: 1..=60 seconds.
    
    A distinct class from [`PyBuildHookTimeout`] and deliberately not interchangeable with
    it — see the module docs.
    """
    MAX_SECS: Final[int]
    """
    The service ceiling for this family: 60.
    """
    def __new__(cls, /, seconds: int) -> RunHookTimeout:
        """
        A run-family timeout, or a refusal naming **both** ceilings.
        
        The message names the other family's limit too, because the caller who hits this is
        nearly always someone who picked a build-hook number: telling them 60 is the limit
        answers a question they did not ask.
        """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def seconds(self, /) -> int: ...

@final
class Sandbox:
    """
    One MicroVM's whole life.
    
    The five transitions are `build_image`, `run`, `suspend`, `resume`, and `terminate`, and
    every state guard lives in the core — see the module docs.
    """
    def __enter__(self, /) -> Sandbox:
        """
        `with sandbox as s:` — returns the sandbox itself.
        """
    def __exit__(self, /, exc_type: Any |None = None, exc_value: Any |None = None, traceback: Any |None = None) -> bool:
        """
        Tears down on the way out, whatever happened inside the block.
        
        Returns `False`, so an exception raised inside the block propagates: the teardown is
        what has to happen, not what has to be reported. Any leak is on the report the
        caller can also get by calling `terminate()` themselves.
        """
    def __new__(cls, /, region: Region) -> Sandbox:
        """
        Resolves credentials for `region` and returns a sandbox with nothing launched.
        
        `region` is a [`PyRegion`] and not a string, which is TRAP-6 at this boundary: the
        five supported regions are named constructors and everything else goes through
        `Region.parse` (refused) or `Region.unlisted` (opted into, at the call site).
        """
    def __repr__(self, /) -> str: ...
    @property
    def bootstrap_count(self, /) -> int:
        """
        How many times the token has been installed. Never above one (STATE-3).
        """
    def build_artifact(self, /, *, name: str, binary: Sequence[int], code_artifact_uri: str, build_role_arn: str, base_image: BaseImage |None = None, dockerfile: str |None = None, inherit_workdir: bool = False) -> bytes:
        """
        The artifact bytes to upload to `code_artifact_uri`.
        
        The upload is the caller's: S3 is not in the core's dependency set. Same parameters
        as [`Self::build_image`] so the bytes a caller puts in the bucket are the bytes the
        build will receive.
        """
    def build_image(self, /, *, name: str, binary: Sequence[int], code_artifact_uri: str, build_role_arn: str, size: SizeClass |None = None, base_image: BaseImage |None = None, dockerfile: str |None = None, repair_guest_identity: bool = False, inherit_workdir: bool = False, run_hook_timeout: RunHookTimeout |None = None, build_hook_timeout: BuildHookTimeout |None = None, tags: dict[str, str] |None = None, log_group: str |None = None, log_stream: str |None = None, token_scope: str |None = None) -> Image:
        """
        Builds an image and waits for it to become usable.
        
        Every local guard runs **before** the call, which matters because the create happens
        after the caller's artifact upload: a rejection AWS raises costs the upload first.
        
        # What is deliberately not a parameter
        
        A `client_token`. There is no such field on the core's request type and none here:
        a digest-derived token replays the original create and wedges an image in `CREATING`
        for fifteen hours with no error at all (TRAP-1). `token_scope` is a CloudTrail
        **label** folded in beside a fresh nonce and cannot become the token.
        
        A `capabilities` list. `repair_guest_identity` is a bool and the request injects
        `["ALL"]` itself, so `["CAP_SYS_ADMIN"]` — the request AWS rejects after the upload
        — is not something a caller can write (TRAP-3).
        
        An `architecture`. The model's enum has exactly one value, so the only thing a field
        could express is a rejected request.
        
        # `log_stream` is a prefix, never the exact stream name
        
        The platform's `logging.logStream` member is an EXACT stream name (prefixes
        unsupported), and one build is three VMs writing three streams — so a fixed name
        would collapse every build's logs into one stream. The client appends `/<16 hex>`
        of fresh randomness per build attempt, and the resolved exact name comes back on
        `Image.log_stream`. `log_stream` requires `log_group`.
        """
    @property
    def endpoint(self, /) -> str |None:
        """
        The proxy endpoint, once launched.
        """
    @property
    def image(self, /) -> Image |None:
        """
        The image, once built.
        """
    @property
    def image_exists(self, /) -> bool:
        """
        Whether an image is recorded as existing (STATE-1).
        """
    @property
    def lifecycle(self, /) -> str:
        """
        The lifecycle state: `"PENDING"`, `"RUNNING"`, `"SUSPENDING"`, `"SUSPENDED"`,
        `"TERMINATING"`, or `"TERMINATED"`.
        
        Spelled as the service spells it, because a reader compares it against a
        `GetMicrovm` response and `Suspended` beside `SUSPENDED` reads like two facts.
        """
    @property
    def microvm_id(self, /) -> str |None:
        """
        The VM id, once launched.
        """
    def resume(self, /) -> Session:
        """
        Thaws the VM and returns a usable session.
        
        # What the core refuses, before any wire call
        
        A resume after `terminate` (STATE-11) — a terminated VM never returns to RUNNING,
        and even a call the service accepted would hand back a different machine. A resume
        from anything but SUSPENDED (STATE-7). And a resume past the launch-time suspended
        window (STATE-12), which is the one worth knowing about: the `idlePolicy` terminates
        a suspended VM once that window passes, so there is nothing left to resume, and
        calling would cost the full poll timeout to learn something worse.
        
        Nothing is re-delivered: no run-hook payload, no token, no bootstrap. The in-memory
        token survived the freeze, and re-delivering it would hit the daemon's one-shot
        bootstrap and be refused — a 409 that reads like a broken VM.
        """
    def run(self, /, *, image_identifier: str |None = None, image_version: str |None = None, execution_role_arn: str |None = None, agent_token: str |None = None, launch_env: dict[str, str] |None = None, egress: bool = False, max_idle_sec: int |None = None, suspended_sec: int |None = None, auto_resume: bool = False, max_duration_sec: int |None = None, ready_timeout: float |None = None, token_scope: str |None = None) -> Session:
        """
        Launches a MicroVM, waits for RUNNING, and returns its session.
        
        # What the core refuses here, and this file does not
        
        A second `run` on one sandbox, with **zero** control-plane calls: the agent token is
        installed at most once per VM lifetime (STATE-3), and a second VM needs a second
        `Sandbox`. A run with no image at all, before any call. Neither check is in this
        file.
        
        `agent_token` is optional because the common case is a per-VM secret nobody needs to
        see; a caller who has one already — a harness minting its own, or a retry that must
        reuse the first attempt's — passes it. It rides in `runHookPayload`, which is what
        keeps it out of the shared image snapshot.
        """
    @property
    def session(self, /) -> Session |None:
        """
        The session, once launched.
        
        A new wrapper each call, all reaching the same session under the same lock. There is
        no cached `Py<PySession>`: caching one would mean a session object that outlives the
        VM it addresses, and the `Held::InSandbox` indirection exists precisely so a
        post-terminate call reports the lifecycle rather than a dangling handle.
        """
    @property
    def state_reason(self, /) -> str |None:
        """
        Why the VM is in its current state, when the service said.
        
        The absence is information: TRAP-8's message distinguishes "no stateReason" from an
        empty one.
        """
    def suspend(self, /) -> str:
        """
        Freezes the VM and waits for the platform to report it.
        
        A freeze and restore rather than a stop and start: the guest keeps its memory, so
        the token, the filesystem, and every exec record survive. The one thing that does
        not is the guest's view of time — it observes the whole suspension as a single jump,
        so any timeout, lease, or TLS session a running command holds expires at once on
        resume.
        
        A suspend from anything but RUNNING is refused by the core with zero control-plane
        calls (STATE-5). Returns the state reached, which may be `"TERMINATED"`: a VM that
        dies while suspending is a state to report rather than an exception out of the
        middle of a teardown.
        """
    @property
    def suspended_window_seconds(self, /) -> float |None:
        """
        The suspended window this sandbox asked for at launch, in seconds.
        
        `None` before a launch, and for a sandbox that did not send the launch — this client
        is the only party that can name the number, because `suspendedDurationSeconds`
        exists only in the `RunMicrovm` request and `GetMicrovm` does not return it.
        """
    def terminate(self, /, *, delete_image: bool = False, delete_log_group: bool = False, delete_attempts: int |None = None, delete_backoff: float |None = None, wait_for_terminated: bool = False) -> TeardownReport:
        """
        Tears down, best-effort, **never raising**.
        
        Order: VM, then image, then the log group last, because the service can recreate a
        group deleted before its image.
        
        Both deletions are opt-in, because both destroy something a caller may still want:
        the image is reusable across runs, and the log group is where a failed build's only
        evidence lives. `delete_log_group=True` **names** the group in
        `report.undeleted` rather than deleting it — CloudWatch is not in the core's
        dependency set, and reporting a leak beats reporting a clean teardown over one.
        
        `wait_for_terminated=False` by default: the caller is on the way out, and a teardown
        that blocked five minutes on a state nobody reads is five minutes of a CI job. The
        report then honestly ends in `"TERMINATING"`.
        """
    @property
    def token_installed(self, /) -> bool:
        """
        Whether the agent token has been installed (STATE-2).
        
        Set by the platform reporting RUNNING, not by the launch call: the run hook is what
        delivers the token, and a launch that died during startup delivered nothing.
        """
    @property
    def was_terminated(self, /) -> bool:
        """
        Whether this VM was ever terminated (STATE-11).
        """

@final
class Session:
    """
    One running MicroVM's control API, with the proxy auth handled for you.
    """
    def __repr__(self, /) -> str: ...
    def connect_headers(self, /, port: int) -> dict[str, str]:
        """
        Both proxy headers for `port`, so a caller can open its **own** connection.
        
        A `dict[str, str]`, for pairing with `endpoint` when something outside this client
        opens a socket to a port on this VM. Minted through the session's existing token
        cache, so this does not burn a second control-plane call and does not open a second
        refresh schedule (TRAP-9).
        
        **Empty for a direct session**, which is the true answer rather than a missing one: a
        daemon reached directly takes no proxy headers.
        
        The auth value is a bearer credential and this returns it. Nothing here logs or
        stores it, and no method *takes* a header map — so a caller cannot feed a forged or
        expired one back in.
        """
    def connect_subprotocols(self, /, port: int) -> list[str] |None:
        """
        The three WebSocket subprotocols for `port`, in the order a handshake offers them.
        
        A MicroVM endpoint takes the auth and the target port as `Sec-WebSocket-Protocol`
        values rather than as headers, because the browser `WebSocket` constructor cannot set
        a header — and the platform strips all three before forwarding, so a server inside
        the VM never negotiates them.
        
        `None` for a direct session, and deliberately not an empty list: the subprotocol form
        exists only for a request through the endpoint proxy, so a list carrying the base
        value with no token would open a handshake refused for a reason naming neither the
        token nor the port.
        
        The middle string carries the credential. Same rule as `connect_headers`.
        """
    @staticmethod
    def direct(endpoint: str, agent_token: str) -> Session:
        """
        A session against a daemon reached **directly**, with no proxy headers.
        
        The shape for a local binary, a test server, or a VM reached over a tunnel. There
        is deliberately no constructor that takes a proxy token: minting one is the
        control plane's job and it happens inside every request (TRAP-9), so a caller
        handing a token in would be handing in one that expires.
        """
    def download_file(self, /, path: str) -> bytes:
        """
        Reads one file.
        """
    def download_tar(self, /, remote: str) -> bytes:
        """
        The raw tar bytes of a remote tree.
        """
    @property
    def endpoint(self, /) -> str:
        """
        The endpoint this session addresses.
        
        A `String` rather than a `&str` because a sandbox-held session reads it under the
        lock, and a reference would outlive the guard.
        """
    def exec(self, /, exec_id: str) -> ExecHandle:
        """
        A handle for an exec started earlier, possibly by another process.
        
        The reattach path. Nothing is checked against the daemon here — the handle is an
        id plus a transport, and a poll is what discovers whether the exec exists.
        """
    def file_exists(self, /, path: str) -> bool:
        """
        Whether a path exists, distinguishing absence from every other refusal.
        """
    def health(self, /) -> Health:
        """
        Unauthenticated liveness.
        """
    def kill(self, /, exec_id: str) -> bool:
        """
        Signals an exec's whole process group. Returns whether anything was signalled.
        """
    @property
    def port(self, /) -> int:
        """
        The port the proxy token is scoped to.
        """
    @property
    def proxy_mint_count(self, /) -> int |None:
        """
        How many proxy tokens this session has minted, or `None` for a direct session.
        
        Exposed because it is the only observable that distinguishes a client which
        re-minted after a resume from one that kept a stale token (STATE-8), and a harness
        asserting on that behaviour needs to be able to read it. The **token itself** is
        not exposed and cannot be: the core's `ProxyToken` has no `Display`, no `as_str`,
        and no `Deref`, so "treat `authToken` as a string" is as inexpressible here as it
        is there (TRAP-7).
        """
    def run(self, /, command: Sequence[str] |str, *, shell: bool = False, cwd: str |None = None, env: dict[str, str] |None = None, user: int |None = None, group: int |None = None, timeout_sec: float |None = None, stdin: bool = False, exec_id: str |None = None) -> ExecHandle:
        """
        Starts a command and returns its handle. Does not wait.
        
        `command` is a list, or a string that becomes a one-element argv — never
        whitespace-split. `shell=True` wants a single script string.
        """
    def run_sync(self, /, command: Sequence[str] |str, *, timeout: float = ..., shell: bool = False, cwd: str |None = None, env: dict[str, str] |None = None, user: int |None = None, group: int |None = None, timeout_sec: float |None = None, stdin: bool = False, exec_id: str |None = None) -> ExecResult:
        """
        Start, wait, ack. The one-shot shape, for when output is all you want.
        """
    def upload_file(self, /, path: str, data: bytes, *, mode: str |None = None) -> None:
        """
        Writes one file, creating parents. `mode` is an **octal string** (`"0755"`), which
        is the daemon's shape — an integer here would be ambiguous between 0o755 and 755.
        """
    def upload_tar(self, /, remote: str, archive: bytes) -> None:
        """
        Extracts pre-built tar bytes under `remote`.
        
        Bytes rather than a local path: packing a directory is the caller's, because the
        symlink and permission decisions in a pack belong to whoever knows what the tree
        means.
        """
    def wait_until_ready(self, /, timeout: float = ...) -> Health:
        """
        Polls health until the daemon reports bootstrapped.
        
        Connection errors on the way are expected rather than exceptional: a VM that has
        just reached RUNNING commonly refuses a connection or two before the proxy path is
        wired up. A *fatal* error ends the wait at once, because retrying a 401 until the
        deadline is the mistake the retryable split exists to prevent.
        """

@final
class SizeClass:
    """
    One of the five documented size classes.
    
    `minimumMemoryInMiB` selects a class; it does not size a VM. Both numbers are on the
    class or neither, because naming only the peak invites budgeting for memory nobody is
    billed for and naming only the baseline invites a pressure test against a ceiling four
    times too low.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def all() -> list[SizeClass]:
        """
        Every class, smallest first.
        """
    @property
    def baseline_gb(self, /) -> float:
        """
        The figure a GB-second rate multiplies. Always the baseline, never the peak.
        """
    @property
    def baseline_mib(self, /) -> int: ...
    @property
    def baseline_vcpu(self, /) -> float: ...
    @staticmethod
    def default_class() -> SizeClass:
        """
        The platform's default, 2048 MiB. Not the smallest — a 0.5 GB baseline fixes the
        guest's always-present ceiling at 2 GB, which OOM-kills a real test suite, and the
        guest has no swap.
        """
    def describe(self, /) -> str:
        """
        One line naming both numbers. `cli.py` calls this `describe()`.
        """
    @staticmethod
    def from_baseline_mib(mib: int) -> SizeClass:
        """
        The class `minimumMemoryInMiB = mib` selects, or a refusal (TRAP-10).
        
        Off-table figures are refused rather than snapped to a neighbour: the two
        plausible readings differ in both memory and rate, and neither has been measured.
        """
    @property
    def peak_gb(self, /) -> float:
        """
        The peak in GB, which is what the guest reports as `MemTotal`.
        """
    @property
    def peak_mib(self, /) -> int: ...
    @property
    def peak_vcpu(self, /) -> float: ...

@final
class StdinAck:
    """
    What a stdin write accomplished.
    """
    def __repr__(self, /) -> str: ...
    @property
    def eof(self, /) -> bool: ...
    @property
    def exec_id(self, /) -> str: ...
    @property
    def written(self, /) -> int: ...

@final
class TeardownReport:
    """
    What a teardown did, and what it left behind.
    
    Returned rather than raised — see the module docs.
    """
    def __repr__(self, /) -> str: ...
    @property
    def failures(self, /) -> list[str]:
        """
        Every failure the teardown swallowed, in the order it hit them.
        
        Kept because a teardown that never raises is a teardown whose failures are
        invisible otherwise, and the first one is usually the cause of the rest.
        """
    @property
    def image_deleted(self, /) -> bool |None:
        """
        Whether the image was deleted, or `None` when deletion was not asked for.
        """
    @property
    def leaked(self, /) -> bool:
        """
        Whether anything a caller asked for was left behind.
        """
    @property
    def lifecycle(self, /) -> str |None:
        """
        The lifecycle state the sandbox ended in.
        
        Commonly `"TERMINATING"` rather than `"TERMINATED"`: the default teardown does not
        wait, so claiming TERMINATED would claim an observation nobody made. Pass
        `wait_for_terminated=True` to observe it.
        """
    @property
    def terminate_accepted(self, /) -> bool:
        """
        Whether the terminate call was accepted.
        """
    def to_dict(self, /) -> dict:
        """
        The report as a dict, for a JSON envelope.
        """
    @property
    def undeleted(self, /) -> list[str]:
        """
        Identifiers of everything a caller asked to have deleted that still exists.
        
        Identifiers rather than a boolean, because a leak nobody can name is a leak nobody
        can clean up. Two things land here: a delete that was attempted and failed, and the
        build **log group**, which this client cannot delete at all.
        """

@final
class Total:
    """
    A report's total, which is a lower bound whenever anything is unpriced.
    
    The core makes `AtLeast { floor, unpriced }` a *different variant* from `Exact`, so a
    lower bound cannot be read without seeing the reasons. Python has no exhaustive match
    to lean on, so the port keeps the floor under a name that says what it is:
    [`Self::floor`], never `total`. A caller reading a field called `total` would have no
    reason to check `is_lower_bound`.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str:
        """
        `at least ~$X (estimated), plus N unpriced (...)` — "at least" leads, because that
        is the whole point.
        """
    @property
    def floor(self, /) -> EstimatedUsd:
        """
        Everything that could be priced. For a lower bound this is **not** the total.
        """
    @property
    def is_lower_bound(self, /) -> bool:
        """
        True when line items with no published rate are missing from the floor.
        """
    @property
    def unpriced_reasons(self, /) -> list[str]:
        """
        Why each unpriced line could not be priced, in report order. Empty for an exact
        total.
        """

@final
class Unpriced:
    """
    A quantity we can measure but cannot price, because no rate is published.
    
    A distinct class rather than `EstimatedUsd("0")`, and the distinction is not cosmetic:
    zero is a claim about the bill, unpriced is a claim about the documentation. `reason`
    is required and not optional, so a line item can say *why*.
    """
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def reason(self, /) -> str: ...

def build_unpriced_reason() -> str:
    """
    Why the image build has no price, as the reason that lands on the line item.
    """

def compare_residency(size: SizeClass, hold_seconds: float, cycles: int = 1, *, rates: RateTable |None = None) -> ResidencyComparison:
    """
    The warm-pool argument, with its own counter-argument attached.
    """

def core_version() -> str:
    """
    The core crate's version, for a `doctor` or `manifest` command to report.
    
    The **core's** version and not this crate's: what a caller needs to know is which client
    they are talking through, and a binding version that drifted from it would be a second
    number nobody can act on.
    """

def cost_constants() -> dict:
    """
    The documented facts a caller may want to assert on, as strings and flags.
    
    A dict rather than a class because it is a transcription of published constants, and
    the Python client publishes the same set. `provenances` and `phases` are here so a
    caller can enumerate the closed sets rather than hardcoding spellings.
    """

def estimate_run(size: SizeClass, *, running_seconds: float = 0.0, suspended_seconds: float = 0.0, image_gb: float |None = None, image_retained_seconds: float |None = None, suspend_resume_cycles: int = 0, snapshot_gb: float |None = None, launched: bool = True, label: str = "plan", rates: RateTable |None = None) -> CostReport:
    """
    What a plan will cost, before spending anything (COST-10).
    
    Takes plain seconds and marks every one of them projected. That is the difference from
    [`run_report`]: not the arithmetic, which is shared, but what the durations admit about
    themselves — and it is why this signature has no `Duration` parameter at all, so an
    accidentally-measured one is not something a caller can write.
    """

def run_report(size: SizeClass, *, running: Duration |None = None, suspended: Duration |None = None, image_build: Duration |None = None, image_gb: float |None = None, image_retained: Duration |None = None, suspend_resume_cycles: int = 0, snapshot_gb: float |None = None, launched: bool = True, label: str = "run", rates: RateTable |None = None) -> CostReport:
    """
    Per-phase attribution for one sandbox's lifecycle.
    
    Every duration parameter takes a [`PyDuration`] and not a number, which is what keeps
    the provenance label attached: passing seconds here would need this function to pick a
    provenance, and the one it would pick is the stronger claim.
    
    `today` is the core's `CalendarDate::today_utc()` rather than a parameter. The core
    takes it so a report is a pure function of its inputs and a test does not have to
    travel in time; a Python caller who needs that reaches for the core through Rust, and
    exposing a date here would be a knob whose only use is faking staleness.
    """

def session_constants() -> dict:
    """
    The daemon's protocol constants, for a caller asserting against the wire contract.
    """

# `microvms_core::VERSION`, added by the module's `#[pymodule_init]`. The **core's**
# version and not this crate's: what a caller needs to know is which client they are
# talking through.
__version__: Final[str] = "0.3.0"

class MicrovmError(Exception):
    """
    Base of every exception this library raises. Carries `.code`, `.kind`, `.wire_kind`,
    and `.retryable` so nothing has to parse a message.
    """
    code: str
    kind: str
    wire_kind: str | None
    retryable: bool

class BuildWedgedError(MicrovmError):
    """
    ERR_BUILD_WEDGED — the image build was never scheduled: the clientToken replay
    signature.
    """

class CredentialsError(MicrovmError):
    """
    ERR_CREDENTIALS — an identity is wrong or absent; waiting will not fix it.
    """

class ExecFailedError(MicrovmError):
    """
    ERR_EXEC_FAILED — the sandbox worked and the command in it exited non-zero. The one
    failure that means nothing is wrong with the platform.
    """

class InterruptedError(MicrovmError):
    """
    ERR_INTERRUPTED — interrupted after launch; teardown ran and any leak is named.
    """

class InvalidArgError(MicrovmError):
    """
    ERR_INVALID_ARG — refused locally, before any AWS call. Every trap closure lands here.
    """

class LaunchDiedError(MicrovmError):
    """
    ERR_LAUNCH_DIED — the MicroVM reached a terminal state before RUNNING. Read the
    message's stateReason.
    """

class PlatformError(MicrovmError):
    """
    ERR_PLATFORM — a control-plane failure with no more specific class.
    """

class PreconditionError(MicrovmError):
    """
    ERR_PRECONDITION — a prerequisite is missing.
    """

class ProtocolError(MicrovmError):
    """
    ERR_PROTOCOL — the daemon rejected the request on its merits. Read `.wire_kind` to
    tell a 400 from a 404.
    """

class RetryableError(MicrovmError):
    """
    ERR_RETRYABLE — transient. Run the identical request again.
    """

class TimeoutError(MicrovmError):
    """
    ERR_TIMEOUT — a client-side deadline elapsed. The VM and the exec are untouched.
    """

class UnexpectedError(MicrovmError):
    """
    ERR_UNEXPECTED — no handler claimed this. A bug in the client, not the platform.
    """

class WindowClosedError(MicrovmError):
    """
    ERR_WINDOW_CLOSED — the launch-time suspended window passed, so there is nothing to
    resume. A longer window has to be set at launch on the next VM.
    """
